backend:
  name: github
  repo: TH01157/inni-queen-germany-guide
  branch: main
  base_url: https://www.inniqueen.com  # Domain của bạn

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Bài viết"
    folder: "src/data/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tiêu đề", name: "title", widget: "string" }
      - { label: "Ngày đăng", name: "date", widget: "datetime" }
      - { label: "Ảnh đại diện", name: "image", widget: "image" }
      - { label: "Danh mục", name: "category", widget: "select", options: ["tinh-yeu-hon-nhan", "loi-song-chua-lanh", "luat-phap", "tai-chinh"] }
      - { label: "Nội dung", name: "body", widget: "markdown" }
backend:
  name: github
  repo: TH01157/inni-queen-germany-guide
  branch: main
  auth_scope: repo
  client_id: "DÁN_CLIENT_ID_VÀO_ĐÂY"
